# which benchmarks to run
benchmarks = '../test/tdce/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.dce_global]
pipeline = [
  "bril2json",
  "python3 dce_global.py",
  "brili -p {args}",
]

[runs.dce_local]
pipeline = [
  "bril2json",
  "python3 dce_local.py",
  "brili -p {args}",
]
